spring.application.name=prw3_2026_AP3

spring.datasource.url=jdbc:h2:file:./DATA/pw3ap3
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
